### ISSUE TITLE
Handle non-string ports

### ISSUE THREAD

**Issue by jmcarp** [18F/cf-service-connect#31]
For example, alphagov/paas-rds-broker sends the port as an int rather than a string. Right now, I get an error like this:

```
Finding the service instance details...
2017/01/11 13:25:58 json: cannot unmarshal number into Go value of type string
```

FWIW, I think this would be simpler if we expressed args with templates, as in https://github.com/18F/cf-service-connect/issues/18#issuecomment-270039745.

**Comment by afeld** [comment]
Sounds like this issue is in the parsing of the service key rather than the calling of the client... the referenced comment is around the latter, so I don't think it would help for this. Not sure of the best way to handle JSON unmarshaling of a field that can be a string or an int...ideas? Also, mind posting a (sanitized) example of the alphagov/paas-rds-broker service key?

**Comment by jmcarp** [comment]
What I'm suggesting is parsing the credentials to `map[string]interface{}` or just `interface{}` and letting the templates render stuff as needed.
